DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS actions;
DROP TABLE IF EXISTS sales_funnels;

CREATE TABLE items (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  cost INT NOT NULL,
  value INT NOT NULL,
  has_service_contract BOOLEAN NOT NULL
);

CREATE TABLE users (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  budget INT NOT NULL
);

CREATE TABLE actions (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  type VARCHAR(250) NOT NULL,
  action CLOB NOT NULL
);

CREATE TABLE sales_funnels (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  state VARCHAR(250) NOT NULL,
  metadata CLOB NOT NULL
);